### Necessário para pegar o token
# @name loginAutenticado
POST http://localhost:40000/Login HTTP/1.1
content-type: application/json

{
    "username": "qwe",
    "password": "qwe"
}
### Seta o token
@accessToken = {{loginAutenticado.response.body.$.token}}

### teste de buscar todos os clientes
GET http://localhost:40000/GetAllClientes HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

### teste de buscar cliente por ID
POST http://localhost:40000/GetClienteByID HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "clienteid": 1
}

### teste de inserção de cliente
POST http://localhost:40000/InsertClientes HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "codigo": "CLI-TESTE",
    "nome": "Cliente de Teste REST",
    "endereco": "Rua API, 123",
    "ativo": true
}

### teste de atualização de cliente
POST http://localhost:40000/UpdateClientes HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "clienteid": 3,
    "codigo": "CLI-TESTE-UPD",
    "nome": "Cliente de Teste REST Alterado",
    "endereco": "Rua API, 321",
    "ativo": false
}

### teste de deleção de cliente
POST http://localhost:40000/DeleteClientes HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "clienteid": 3
}